### ISSUE TITLE
Develop content/copy

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/tap-deck#1]
Using [this](https://github.com/pdxruby/preshow) as a template.

**Comment by jjhampton** [comment]
I added @jdspringr07 as a collaborator w/ write access to this repo - so he can create new branches / push / pull etc.

**Comment by davidmolina** [comment]
@jdspringr07 Do you want to take the first stab on this?

**Comment by johannes-cabal** [comment]
@davidmolina Working on it now. I'll most likely commit and push as I get each page setup. I'll need to collaborate on content. Not really sure what all we should be tossing in here for a generic "taps" class.

**Comment by davidmolina** [comment]
Sure thing.

**Comment by davidmolina** [comment]
Closing this issue as #11 addresses much of this.
