### ISSUE TITLE
Determine contents of tap-deck

### ISSUE THREAD

**Issue by johannes-cabal** [OperationCode/tap-deck#11]
@davidmolina - What kind of content would you like included? Right now, I have the landing page with logo and mission. The second slide contains a video link. I just want to make sure that everyone has input as to what should be a part of the military separation briefing.

**Comment by davidmolina** [comment]
A few recommendations:
- Programs & Services, ex. Software Mentor Protégé Program, Deploy, Scholarships, Conferences, etc
- Slack and programming channels 
- A map with code schools across the U.S., and campus vs. online-only 
- Types of jobs avail and salary range
- Social Media: Twitter, FB, LinkedIn, Instagram, Meetup

**Comment by johannes-cabal** [comment]
1) Introduction Slide
2) Missions and Goals
- Software Mentorship
- Scholarships
- Employer Services
- Advocacy

3) On a mission to expand GI-Bill Video
4) Mentorships - how do we provide it? Include screenshots, potentially video clips, etc.
5) Scholarships - how we provide the gap between VA and code schools/conference

6) Employer Services
- Resume Support
- Placement Services
- Apprenticeship 
- Veteran Network for skill sets

7) Remain decentralized, worldwide, 
- GI Bill accredited at every school
- Vets go through OperationCode to assist with paperwork, enrollment, etc

8) Advocacy 
- "We will defend" veterans from predators and scams from non-legitimate Code Schools. We ensure Code Schools are legitimate. 
- Code Schools are non-regulated. We aide in navigating the waters. 

9) Nationwide Fundraisers
10) Get early involvement in coding to easily transition into Software Engineering 
11) Long Term goals

**Comment by davidmolina** [comment]
Thanks @jdspringr07 for taking notes on the conference call. Let's give this a go.

**Comment by davidmolina** [comment]
@jdspringr07 So about 11 slides? How much do we get in front of transitioning military?

**Comment by kevinfalting** [comment]
Oh, this is good. I'll start putting in the information as I get time.

**Comment by kevinfalting** [comment]
What's with the timer on the slides?

**Comment by davidmolina** [comment]
Timer?

**Comment by kevinfalting** [comment]
On each slide there is a timer that auto-advances each slide. It's at the bottom left corner of the screen.

**Comment by johannes-cabal** [comment]
I tossed that in to play around with. In some presentations, I've had an auto transition in place to keep me on pace for my time limit, but also added in the ability to stop auto-transition. 

If you guys don't want that in, you can remove it from the index.html or can play around with the timer. 

`
189         autoSlide: 20000, 
190         autoSlideStoppable: true, 
`
Also, Kevin, as a heads up - there's a lot of magic coming in with reveal.js. I'd recommend taking a look at their documentation for some of the cool stuff you can do. :)

**Comment by kevinfalting** [comment]
Very nice. I don't mind the timer, I was just wondering what it was for.

I've seen reveal.js in action before, just have never used it myself. I mostly just added the content and the html to support it for each slide.

I also added a javascript calculator that automatically injects the correct date. This way it's always current.

**Comment by davidmolina** [comment]
@KevinRoss- just merged it in and tried it locally. It's awesome and should do the trick. The more we present out at mil bases and veterans-groups and gain feedback (through Q&A) the more we can refine it. 

One area is the video. Can't be played unless there's internet access. Wondering if there's a way around this? Given that some places we might not have internet access.

**Comment by johannes-cabal** [comment]
@davidmolina - I was wondering this as well. Are you able to download the video locally from Vimeo? If so, you could probably make a loop to check for the website, when it cannot connect, look for the file locally?

That way it can be viewed online and offline.

**Comment by davidmolina** [comment]
http://operationcode.org/media
